# Generated by Django 3.2.6 on 2021-09-10 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='quntity',
            new_name='qunatity',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Zipcode',
            field=models.IntegerField(),
        ),
    ]
