# Generated by Django 4.0 on 2022-01-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_quantity_orderplaced_qunatity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancle')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Loptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('CS', 'Cooking Essentials'), ('GG', 'General Grocery'), ('PC', 'Personal Care '), ('CU', 'Cleaning Utility'), ('B', 'Beverages')], max_length=2),
        ),
    ]
