# Generated by Django 4.0 on 2022-01-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_product_stock_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
