# Generated by Django 4.0 on 2022-01-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_orderplaced_options_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='shipping_address',
            field=models.CharField(default='uttara, Dhaka', max_length=250),
            preserve_default=False,
        ),
    ]
